title:             Den's blog
email:             nilotic2@gmail.com
description:       Summarized WWDC sessions
author:            Den Jo
baseurl:           "/WWDC"
url:               "http://nilotic.github.io"

# Social Profiles
twitter_username:  nilotic2
github_username:   nilotic
facebook_username: nilotic

# Build settings
markdown:          kramdown
paginate:          50
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
