title:             Den's Blog
email:             nilotic2@gmail.com
description:       Summaried WWDC sessions
author:            Den
baseurl:           "/wwdc"
url:               "http://nilotic.github.io"
theme:             jekyll-theme-clean-blog

# Social Profiles
twitter_username:  nilotic
github_username:   nilotic
facebook_username: nilotic

# Build settings
markdown:          kramdown
paginate:          50
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

